import { useEffect, useMemo, useState } from "react";

const API_BASE = (import.meta.env.VITE_API_URL || import.meta.env.VITE_BACKEND_URL || "https://awaazrajasthan.onrender.com").replace(/\/$/, "");
const E_PAPER_URL = import.meta.env.VITE_E_PAPER_URL || "/epaper";
const VAPID_PUBLIC_KEY = import.meta.env.VITE_VAPID_PUBLIC_KEY || "";

const categories = ["होम", "राजस्थान", "जयपुर", "जोधपुर", "उदयपुर", "कोटा", "अजमेर", "भीलवाड़ा", "बीकानेर", "अलवर", "अपराध", "राजनीति", "शिक्षा", "नौकरी", "खेल", "देश", "दुनिया", "मनोरंजन", "बिजनेस"];
const districts = ["अजमेर", "अलवर", "बालोतरा", "बांसवाड़ा", "बारां", "बाड़मेर", "ब्यावर", "भरतपुर", "भीलवाड़ा", "बीकानेर", "बूंदी", "चित्तौड़गढ़", "चूरू", "दौसा", "डीग", "धौलपुर", "डीडवाना-कुचामन", "डूंगरपुर", "हनुमानगढ़", "जयपुर", "जैसलमेर", "जालोर", "झालावाड़", "झुंझुनूं", "जोधपुर", "करौली", "खैरथल-तिजारा", "कोटा", "कोटपूतली-बहरोड़", "नागौर", "पाली", "फलोदी", "प्रतापगढ़", "राजसमंद", "सलूम्बर", "सवाई माधोपुर", "सीकर", "सिरोही", "श्रीगंगानगर", "टोंक", "उदयपुर"];

const fallbackNews = [
  { id: "f1", category: "राजस्थान", location: "राजस्थान", title: "राजस्थान की बड़ी खबरें और जरूरी अपडेट एक जगह", excerpt: "प्रदेश के जिलों, प्रशासन, मौसम, शिक्षा, रोजगार और जनहित से जुड़ी प्रमुख खबरों पर हमारी नजर।", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1500&q=85", time: "अभी", author: "आवाज़ राजस्थान" },
  { id: "f2", category: "जयपुर", location: "जयपुर", title: "जयपुर से सामने आईं दिन की प्रमुख स्थानीय खबरें", excerpt: "शहर की गतिविधियों और नागरिक मुद्दों से जुड़े महत्वपूर्ण अपडेट।", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=85", time: "12 मिनट पहले" },
  { id: "f3", category: "खेल", location: "राजस्थान", title: "खेल जगत में आज के अहम मुकाबलों और खिलाड़ियों की खबरें", excerpt: "राज्य और देश के खेल जगत से ताजा अपडेट।", image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=85", time: "28 मिनट पहले" },
  { id: "f4", category: "देश", location: "भारत", title: "देशभर की प्रमुख खबरों पर एक नजर", excerpt: "राष्ट्रीय स्तर पर दिनभर के जरूरी घटनाक्रम और अपडेट।", image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1000&q=85", time: "42 मिनट पहले" },
  { id: "f5", category: "अपराध", location: "राजस्थान", title: "पुलिस और प्रशासन से जुड़े महत्वपूर्ण अपडेट", excerpt: "आधिकारिक सूचनाओं और स्थानीय घटनाओं की प्रमुख जानकारी।", image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1000&q=85", time: "1 घंटा पहले" },
  { id: "f6", category: "बिजनेस", location: "राजस्थान", title: "कारोबार और बाजार से जुड़े जरूरी अपडेट", excerpt: "व्यापार, बाजार और अर्थव्यवस्था से जुड़ी प्रमुख खबरें।", image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1000&q=85", time: "1 घंटा पहले" }
];

const icons = {
  menu: <svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16" /></svg>,
  search: <svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" /></svg>,
  bell: <svg viewBox="0 0 24 24"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></svg>,
  home: <svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z" /></svg>,
  bookmark: <svg viewBox="0 0 24 24"><path d="M6 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18l-6-3-6 3z" /></svg>,
  share: <svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5" /><circle cx="6" cy="12" r="2.5" /><circle cx="18" cy="19" r="2.5" /><path d="m8.3 10.8 7.4-4.5M8.3 13.2l7.4 4.5" /></svg>,
  arrow: <svg viewBox="0 0 24 24"><path d="M5 12h13M13 6l6 6-6 6" /></svg>,
  close: <svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18" /></svg>,
  clock: <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></svg>,
  map: <svg viewBox="0 0 24 24"><path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3zM9 3v15M15 6v15" /></svg>,
  camera: <svg viewBox="0 0 24 24"><path d="M4 7h4l2-3h4l2 3h4v13H4z" /><circle cx="12" cy="13" r="3.5" /></svg>,
  sun: <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4" /><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" /></svg>,
  jobs: <svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="13" rx="2" /><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18" /></svg>,
  video: <svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m10 9 5 3-5 3z" /></svg>,
  play: <svg viewBox="0 0 24 24"><path d="m9 7 9 5-9 5z" /></svg>,
  newspaper: <svg viewBox="0 0 24 24"><path d="M5 4h14a1 1 0 0 1 1 1v14H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z" /><path d="M7 8h9M7 12h9M7 16h6" /></svg>
};
function Icon({ name }) { return <span className="svg-icon">{icons[name]}</span>; }
function normalizeNews(item, index) {
  return { id: item._id || item.id || `api-${index}`, category: item.category || "राजस्थान", location: item.location || item.city || "राजस्थान", title: item.title || item.headline || "ताजा खबर", excerpt: item.excerpt || item.summary || item.description || "", image: item.image || item.imageUrl || item.thumbnail || fallbackNews[index % fallbackNews.length].image, time: item.publishedAt || item.createdAt ? new Date(item.publishedAt || item.createdAt).toLocaleString("hi-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }) : item.time || "अभी", author: item.author || item.reporter || "आवाज़ राजस्थान" };
}
function BrandMark({ small = false }) { return <div className={`brand-mark ${small ? "small" : ""}`} aria-hidden="true"><img src="/awaazrajasthan-logo.png" alt="आवाज़ राजस्थान" /></div>; }
function AdSlot({ position = "home_top", className = "" }) {
  const [ad, setAd] = useState(null);
  useEffect(() => {
    if (!API_BASE) return;
    let cancelled = false;
    const device = window.innerWidth < 768 ? "mobile" : "desktop";
    fetch(`${API_BASE}/api/ads?position=${encodeURIComponent(position)}&device=${device}`)
      .then(r => r.ok ? r.json() : Promise.reject())
      .then(data => { const list = Array.isArray(data) ? data : data.ads || data.data || []; if (!cancelled && list[0]) setAd(list[0]); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [position]);
  useEffect(() => {
    if (!API_BASE || !ad) return;
    const id = ad._id || ad.id;
    if (!id) return;
    fetch(`${API_BASE}/api/ads/${id}/impression`, { method: "POST" }).catch(() => {});
  }, [ad]);
  if (!ad) return <div className={`ad-slot ${className}`}><span>विज्ञापन</span></div>;
  const id = ad._id || ad.id; const image = ad.image || ad.imageUrl || ad.banner;
  return <a className={`ad-slot ad-live ${className}`} href={ad.link || "#"} target="_blank" rel="noreferrer" onClick={() => API_BASE && fetch(`${API_BASE}/api/ads/${id}/click`, { method: "POST" }).catch(() => {})}>{image ? <img src={image} alt={ad.title || "विज्ञापन"} /> : <b>{ad.title || "विज्ञापन"}</b>}</a>;
}
function SectionTitle({ kicker, title, action, onAction }) { return <div className="section-title"><div><span>{kicker}</span><h2>{title}</h2></div>{action && <button onClick={onAction}>{action}<Icon name="arrow" /></button>}</div>; }
function NewsImage({ item, large = false }) { return <div className={`news-image ${large ? "large" : ""}`}><img src={item.image} alt="" loading={large ? "eager" : "lazy"} /><span className="image-category">{item.category}</span></div>; }
function NewsRow({ item, onOpen, bookmarked, onBookmark, onShare }) { return <article className="news-row" onClick={() => onOpen(item)}><NewsImage item={item} /><div className="news-row-body"><div className="meta"><span>{item.location}</span><span><Icon name="clock" />{item.time}</span></div><h3>{item.title}</h3>{item.excerpt && <p>{item.excerpt}</p>}<div className="row-tools" onClick={e => e.stopPropagation()}><button className={bookmarked ? "active" : ""} aria-label="बुकमार्क" onClick={() => onBookmark(item.id)}><Icon name="bookmark" /></button><button aria-label="शेयर" onClick={() => onShare(item)}><Icon name="share" /></button></div></div></article>; }

function App() {
  const [news, setNews] = useState(fallbackNews); const [activeCategory, setActiveCategory] = useState("होम"); const [district, setDistrict] = useState(""); const [search, setSearch] = useState(""); const [searchOpen, setSearchOpen] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [notificationOpen, setNotificationOpen] = useState(false); const [article, setArticle] = useState(null); const [bookmarks, setBookmarks] = useState(() => { try { return JSON.parse(localStorage.getItem("awaaz-bookmarks") || "[]"); } catch { return []; } }); const [savedOnly, setSavedOnly] = useState(false); const [notificationState, setNotificationState] = useState("idle"); const [toast, setToast] = useState(""); const [districtQuery, setDistrictQuery] = useState("");
  useEffect(() => { document.documentElement.lang = "hi"; if (!API_BASE) return; let cancelled = false; fetch(`${API_BASE}/api/news?limit=100`).then(r => r.ok ? r.json() : Promise.reject()).then(data => { const list = Array.isArray(data) ? data : data.news || data.data || []; if (!cancelled && list.length) setNews(list.map(normalizeNews)); }).catch(() => {}); return () => { cancelled = true; }; }, []);
  useEffect(() => { localStorage.setItem("awaaz-bookmarks", JSON.stringify(bookmarks)); }, [bookmarks]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(""), 2300); return () => clearTimeout(t); }, [toast]);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return news.filter(item => { const categoryMatch = activeCategory === "होम" || item.category === activeCategory || item.location === activeCategory; const districtMatch = !district || item.location === district || item.category === district; const termMatch = !term || [item.title, item.excerpt, item.category, item.location].join(" ").toLowerCase().includes(term); const savedMatch = !savedOnly || bookmarks.includes(String(item.id)); return categoryMatch && districtMatch && termMatch && savedMatch; }); }, [news, activeCategory, district, search, savedOnly, bookmarks]);
  const displayNews = filtered.length ? filtered : (!search && !savedOnly && !district && activeCategory === "होम" ? news : []); const featured = displayNews[0]; const sideStories = displayNews.slice(1, 4); const latest = displayNews.slice(featured ? 1 : 0); const trending = [...news].slice(0, 5); const districtFiltered = districts.filter(d => d.includes(districtQuery.trim())).slice(0, 20);
  function selectCategory(category) { setActiveCategory(category); setDistrict(""); setSavedOnly(false); setMenuOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function selectDistrict(name) { setDistrict(name); setActiveCategory("होम"); setSavedOnly(false); setToast(`${name} की खबरें चुनी गईं`); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function toggleBookmark(id) { const key = String(id); setBookmarks(prev => prev.includes(key) ? prev.filter(x => x !== key) : [...prev, key]); setToast(bookmarks.includes(key) ? "बुकमार्क हटाया गया" : "खबर सेव हो गई"); }
  async function share(item) { const url = `${window.location.origin}${window.location.pathname}#news-${item.id}`; try { if (navigator.share) await navigator.share({ title: item.title, text: item.excerpt, url }); else { await navigator.clipboard.writeText(url); setToast("लिंक कॉपी हो गया"); } } catch {} }
  async function openArticle(item) { setArticle(item); if (API_BASE && item.id && !String(item.id).startsWith("f")) fetch(`${API_BASE}/api/news/${item.id}`).catch(() => {}); window.history.replaceState(null, "", `#news-${item.id}`); }
  async function enableNotifications() { if (!("Notification" in window) || !("serviceWorker" in navigator)) { setNotificationState("unsupported"); return; } if (!VAPID_PUBLIC_KEY) { setNotificationState("config"); return; } try { setNotificationState("loading"); const permission = await Notification.requestPermission(); if (permission !== "granted") { setNotificationState("denied"); return; } const registration = await navigator.serviceWorker.ready; const normalized = VAPID_PUBLIC_KEY.replace(/-/g, "+").replace(/_/g, "/"); const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "="); const key = Uint8Array.from(atob(padded), c => c.charCodeAt(0)); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: key }); if (API_BASE) await fetch(`${API_BASE}/api/notifications/subscribe`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(subscription) }); setNotificationState("enabled"); } catch { setNotificationState("error"); } }

  return <div className="app-shell">
    <div className="utility-bar"><div className="site-container utility-inner"><span>राजस्थान की हर खबर • हर जिले की आवाज</span><span className="utility-right">सच्ची पत्रकारिता • जनहित सर्वोपरि</span></div></div>
    <header className="site-header"><div className="site-container header-main"><button className="mobile-icon" onClick={() => setMenuOpen(true)} aria-label="मेन्यू"><Icon name="menu" /></button><button className="brand" onClick={() => selectCategory("होम")} aria-label="आवाज़ राजस्थान होम"><BrandMark /><span className="brand-copy"><strong><em>आवाज़</em> राजस्थान</strong><small>आपकी आवाज़ • आपका राजस्थान</small></span></button><div className="brand-tagline"><b>राजस्थान की हर खबर</b><span>हर जिले की आवाज</span></div><div className="header-actions"><button onClick={() => setSearchOpen(v => !v)} aria-label="खोजें"><Icon name="search" /></button><button className="notification-button" onClick={() => setNotificationOpen(v => !v)} aria-label="नोटिफिकेशन"><Icon name="bell" /><i /></button><button className="desktop-menu" onClick={() => setMenuOpen(true)} aria-label="मेन्यू"><Icon name="menu" /></button></div>{notificationOpen && <div className="notification-pop"><b>ताजा खबरों की सूचना</b><p>ब्रेकिंग न्यूज़ और जरूरी राजस्थान अपडेट सीधे अपने डिवाइस पर पाएं।</p><button onClick={enableNotifications}>{notificationState === "enabled" ? "नोटिफिकेशन चालू हैं" : notificationState === "loading" ? "चालू हो रहा है..." : "नोटिफिकेशन चालू करें"}</button>{notificationState === "config" && <small>VAPID key configure होने के बाद push notification उपलब्ध होगा।</small>}</div>}</div><div className="category-nav"><div className="site-container nav-scroll">{categories.map(c => <button key={c} className={activeCategory === c && !district ? "active" : ""} onClick={() => selectCategory(c)}>{c}</button>)}</div></div>{searchOpen && <div className="search-strip"><div className="site-container search-box"><Icon name="search" /><input autoFocus value={search} onChange={e => setSearch(e.target.value)} placeholder="खबर, जिला या विषय खोजें..." /><button onClick={() => { setSearch(""); setSearchOpen(false); }}><Icon name="close" /></button></div></div>}</header>
    <div className="breaking-bar"><div className="site-container breaking-inner"><b className="breaking-label"><i /> ब्रेकिंग</b><div className="breaking-track"><span>{news[0]?.title || "राजस्थान की ताजा खबरें"}</span><span>{news[1]?.title || "हर जिले की जरूरी अपडेट्स"}</span><span>{news[2]?.title || "आवाज़ राजस्थान पर पढ़ें"}</span></div><button onClick={() => selectCategory("राजस्थान")}><Icon name="arrow" /></button></div></div>
    <main><div className="site-container page-top"><AdSlot position="home_top" className="top-ad" />
      <section className="hero-section"><div className="section-intro"><div><span className="eyebrow">{district ? `${district} न्यूज़` : "आज की सबसे बड़ी खबर"}</span><h1>{district ? `${district} की ताजा खबरें` : "राजस्थान की हर खबर, आपकी नजर में"}</h1></div><div className="live-pill"><i /> LIVE UPDATES</div></div>{featured ? <div className="hero-grid"><article className="featured-card" onClick={() => openArticle(featured)}><NewsImage item={featured} large /><div className="featured-content"><div className="meta"><span>{featured.location}</span><span><Icon name="clock" />{featured.time}</span></div><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="featured-footer"><button>पूरी खबर पढ़ें <Icon name="arrow" /></button><span>{featured.author}</span></div></div></article><div className="hero-side">{sideStories.map(item => <article key={item.id} className="mini-card" onClick={() => openArticle(item)}><NewsImage item={item} /><div><div className="meta"><span>{item.location}</span><span>{item.time}</span></div><h3>{item.title}</h3></div></article>)}</div></div> : <div className="empty-state"><b>इस फिल्टर में अभी खबर उपलब्ध नहीं है।</b><button onClick={() => { setSearch(""); setDistrict(""); setSavedOnly(false); selectCategory("होम"); }}>होम पर जाएं</button></div>}</section>
      <section className="quick-links"><button onClick={() => window.location.href = E_PAPER_URL}><span className="quick-icon"><Icon name="newspaper" /></span><b>ई-पेपर</b><small>आज का अखबार</small></button><button onClick={() => setToast("लाइव टीवी मॉड्यूल जल्द उपलब्ध होगा")}><span className="quick-icon live"><Icon name="video" /></span><b>लाइव टीवी</b><small>24×7 अपडेट</small></button><button onClick={() => setToast("वीडियो सेक्शन जल्द उपलब्ध होगा")}><span className="quick-icon"><Icon name="play" /></span><b>वीडियो</b><small>देखें सभी</small></button><button onClick={() => setToast("फोटो गैलरी जल्द उपलब्ध होगी")}><span className="quick-icon"><Icon name="camera" /></span><b>फोटो गैलरी</b><small>तस्वीरों में खबर</small></button><button onClick={() => setToast("मौसम मॉड्यूल जल्द उपलब्ध होगा")}><span className="quick-icon"><Icon name="sun" /></span><b>मौसम</b><small>आज का हाल</small></button><button onClick={() => selectCategory("नौकरी")}><span className="quick-icon"><Icon name="jobs" /></span><b>रोजगार</b><small>सरकारी नौकरी</small></button></section>
      <section className="district-section"><SectionTitle kicker="RAJASTHAN CONNECT" title="41 जिलों की खबरें" action="सभी जिले" onAction={() => { setDistrict(""); setMenuOpen(true); }} /><div className="district-toolbar"><div className="district-search"><Icon name="search" /><input value={districtQuery} onChange={e => setDistrictQuery(e.target.value)} placeholder="जिला खोजें (जैसे जयपुर, जोधपुर...)" /></div><div className="district-mode"><button className="active"><Icon name="map" /> जिलों से चुनें</button><button>सूची से चुनें</button></div></div><div className="district-panel"><div className="rajasthan-shape"><div className="map-dot dot-1" /><div className="map-dot dot-2" /><div className="map-dot dot-3" /><strong>RAJASTHAN</strong><span>41 DISTRICTS</span></div><div className="district-grid">{districtFiltered.map(d => <button key={d} className={district === d ? "selected" : ""} onClick={() => selectDistrict(d)}>{d}<Icon name="arrow" /></button>)}</div></div></section>
      <div className="content-grid"><section className="latest-section"><SectionTitle kicker="LATEST NEWS" title={district || activeCategory === "होम" ? "राजस्थान की बड़ी खबरें" : `${activeCategory} की खबरें`} action="सभी देखें" onAction={() => { setSavedOnly(false); setSearch(""); }} />{latest.length ? latest.map(item => <NewsRow key={item.id} item={item} onOpen={openArticle} bookmarked={bookmarks.includes(String(item.id))} onBookmark={toggleBookmark} onShare={share} />) : <div className="empty-state">कोई खबर नहीं मिली।</div>}</section><aside className="sidebar"><AdSlot position="sidebar" className="sidebar-ad" /><div className="side-widget"><div className="widget-head"><div><span>TOP STORIES</span><h3>सबसे ज्यादा पढ़ी गई</h3></div><b>🔥</b></div>{trending.map((item, i) => <button key={item.id} className="trend-item" onClick={() => openArticle(item)}><strong>{String(i + 1).padStart(2, "0")}</strong><span>{item.title}</span></button>)}</div><div className="epaper-widget"><div className="paper-preview"><i /><i /><i /><i /><i /></div><div><span>आज का संस्करण</span><b>आवाज़ राजस्थान ई-पेपर</b><small>पूरे अखबार को डिजिटल रूप में पढ़ें</small></div><button onClick={() => window.location.href = E_PAPER_URL}>ई-पेपर पढ़ें <Icon name="arrow" /></button></div></aside></div>
      <AdSlot position="home_inline" className="inline-ad" />
      <section className="category-highlights"><SectionTitle kicker="MORE FROM RAJASTHAN" title="हर विषय की खबर" /><div className="highlight-grid">{["अपराध", "शिक्षा", "खेल", "बिजनेस"].map(cat => { const item = news.find(n => n.category === cat) || news[(categories.indexOf(cat) + 1) % news.length]; return <article key={cat} onClick={() => item && openArticle(item)}><NewsImage item={item || fallbackNews[0]} /><div><span>{cat}</span><h3>{item?.title || `${cat} से जुड़ी ताजा खबरें`}</h3></div></article>; })}</div></section>
    </div></main>
    <footer className="site-footer"><div className="site-container footer-grid"><div><div className="footer-brand"><BrandMark small /><span><b>आवाज़ राजस्थान</b><small>आपकी आवाज़ • आपका राजस्थान</small></span></div><p>राजस्थान के हर जिले की खबर, जिम्मेदार और तथ्यपरक तरीके से।</p></div><div><b>मुख्य सेक्शन</b><button onClick={() => selectCategory("राजस्थान")}>राजस्थान</button><button onClick={() => selectCategory("अपराध")}>अपराध</button><button onClick={() => selectCategory("शिक्षा")}>शिक्षा</button></div><div><b>हमसे जुड़ें</b><button onClick={() => setNotificationOpen(true)}>नोटिफिकेशन</button><button onClick={() => setMenuOpen(true)}>सभी सेक्शन</button><button onClick={() => setSavedOnly(true)}>सेव की गई खबरें</button></div></div><div className="footer-bottom">© {new Date().getFullYear()} आवाज़ राजस्थान • सभी अधिकार सुरक्षित</div></footer>
    <nav className="mobile-bottom"><button className={activeCategory === "होम" && !savedOnly ? "active" : ""} onClick={() => selectCategory("होम")}><Icon name="home" /><span>होम</span></button><button onClick={() => { setSavedOnly(false); setSearchOpen(true); }}><Icon name="search" /><span>खोजें</span></button><button className={district ? "active" : ""} onClick={() => setMenuOpen(true)}><Icon name="map" /><span>जिले</span></button><button onClick={() => setToast("लाइव सेक्शन जल्द उपलब्ध होगा")}><Icon name="video" /><span>लाइव</span></button><button className={savedOnly ? "active" : ""} onClick={() => { setSavedOnly(true); setActiveCategory("होम"); setDistrict(""); }}><Icon name="bookmark" /><span>सेव</span></button></nav>
    {menuOpen && <div className="drawer-backdrop" onClick={() => setMenuOpen(false)}><aside className="drawer" onClick={e => e.stopPropagation()}><div className="drawer-head"><button className="brand" onClick={() => selectCategory("होम")}><BrandMark small /><span className="brand-copy"><strong><em>आवाज़</em> राजस्थान</strong><small>आपकी आवाज़ • आपका राजस्थान</small></span></button><button className="drawer-close" onClick={() => setMenuOpen(false)}><Icon name="close" /></button></div><div className="drawer-list"><b>मुख्य सेक्शन</b>{categories.filter(c => c !== "होम").map(c => <button key={c} onClick={() => selectCategory(c)}>{c}<Icon name="arrow" /></button>)}<b className="drawer-sub">विशेष</b><button onClick={() => { setMenuOpen(false); setDistrictQuery(""); window.scrollTo({ top: 1100, behavior: "smooth" }); }}>41 जिलों की खबरें<Icon name="map" /></button><button onClick={() => { setMenuOpen(false); window.location.href = E_PAPER_URL; }}>ई-पेपर<Icon name="newspaper" /></button><button onClick={() => { setMenuOpen(false); setNotificationOpen(true); }}>नोटिफिकेशन<Icon name="bell" /></button></div></aside></div>}
    {article && <div className="article-backdrop" onClick={() => { setArticle(null); window.history.replaceState(null, "", window.location.pathname); }}><article className="article-modal" onClick={e => e.stopPropagation()}><button className="article-close" onClick={() => setArticle(null)}><Icon name="close" /></button><img src={article.image} alt="" /><div className="article-content"><div className="article-meta"><span>{article.category}</span><span>{article.location}</span><span>{article.time}</span></div><h1>{article.title}</h1><p className="article-excerpt">{article.excerpt}</p><div className="article-actions"><button className={bookmarks.includes(String(article.id)) ? "active" : ""} onClick={() => toggleBookmark(article.id)}><Icon name="bookmark" /> सेव करें</button><button onClick={() => share(article)}><Icon name="share" /> शेयर करें</button></div><div className="article-copy"><p>{article.excerpt || "आवाज़ राजस्थान की टीम से प्राप्त जानकारी के आधार पर यह खबर तैयार की गई है। अधिकृत और विस्तृत अपडेट उपलब्ध होने पर इस पेज को अपडेट किया जा सकता है।"}</p><p>आवाज़ राजस्थान का उद्देश्य राजस्थान के पाठकों तक स्थानीय और महत्वपूर्ण समाचारों को स्पष्ट, जिम्मेदार और आसान भाषा में पहुंचाना है।</p></div></div></article></div>}
    {toast && <div className="toast">{toast}</div>}
  </div>;
}
export default App;
